name: Build

#on: [push, pull_request]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lerna:build-all


