name: Publish Packages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git checkout "${GITHUB_REF:11}"
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run lerna:build-all

#  publish-npm:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#          registry-url: https://registry.npmjs.org/
#      - run: npm ci
#      - run: npm run lerna:publish -- --yes --force-publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
