name: Publish Prerelease

on: workflow_dispatch

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Configure Git User
        uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          global: true
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Node Setup
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: |
          npm ci
          npm run lerna:build-all
      - name: Publish
        run: npm run lerna:publish-prerelease
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
